#include "techpulse/sources/github.hpp"
#include "techpulse/normalize/normalize.hpp"
#include <cctype>
namespace techpulse::sources { namespace {
std::string field(const std::string& s,const std::string& n){auto p=s.find("\""+n+"\"");if(p==std::string::npos)return{};p=s.find(':',p);p=s.find_first_not_of(" \t",p+1);if(p==std::string::npos||s[p]!='"')return{};auto e=s.find('"',p+1);return e==std::string::npos?"":s.substr(p+1,e-p-1);}
std::string last_field(const std::string& s,const std::string& n){auto p=s.rfind("\""+n+"\"");if(p==std::string::npos)return{};p=s.find(':',p);p=s.find_first_not_of(" \t",p+1);auto e=s.find('"',p+1);return p==std::string::npos||e==std::string::npos?"":s.substr(p+1,e-p-1);}
int number(const std::string&s,const std::string&n){auto p=s.find("\""+n+"\"");if(p==std::string::npos)return 0;try{return std::stoi(s.substr(s.find(':',p)+1));}catch(...){return 0;}}
std::string encode(std::string s){std::string r;for(unsigned char c:s){if(std::isalnum(c)||c=='-'||c=='_')r+=c;else {const char* h="0123456789ABCDEF";r+='%';r+=h[c>>4];r+=h[c&15];}}return r;}
} FetchResult fetch_github_repositories(const std::string& query,const HttpGet& get){FetchResult r;auto x=get("https://api.github.com/search/repositories?q="+encode(query)+"&sort=updated&order=desc&per_page=10");if(x.status!=200){r.errors.push_back("GitHub search returned HTTP "+std::to_string(x.status)+(x.error.empty()?"":": "+x.error));return r;}size_t p=x.body.find("\"items\"");while((p=x.body.find("\"full_name\"",p))!=std::string::npos){auto end=x.body.find("\"full_name\"",p+11);auto o=x.body.substr(p,end==std::string::npos?std::string::npos:end-p);model::RadarItem i;i.source_type="github";i.source_id=field(o,"full_name");if(i.source_id.empty()){p+=11;continue;}i.id="github:"+i.source_id;i.title=i.source_id;i.summary_raw=field(o,"description");i.url=normalize::canonical_url(last_field(o,"html_url"));i.published_at=field(o,"updated_at");i.metrics.stars=number(o,"stargazers_count");i.provenance.push_back({"github",i.source_id,i.url});r.items.push_back(std::move(i));p=end==std::string::npos?x.body.size():end;}return r;} }
